version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7
      - test-3.6
      - test-2.7
jobs:
  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Open Jdk 8
          command: |
            sudo apt-get install openjdk-8-jdk
            JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
            PATH=$JAVA_HOME/bin:$PATH
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin
      - run:
          name: Install nvm and node
          command: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
            echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
            echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
            nvm install 8.10
            npm --version
            node --version
      - run:
          name: Install code
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            make init
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make pr
            pytest -vv tests/integration

  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7